### ISSUE TITLE
feat: Add annotations to Dashy Helm Chart

### ISSUE THREAD

**Issue by imchristianlowe** [vyrtualsynthese/selfhosted-helmcharts#85]
# Feature Request

**Describe the Feature Request**

Add optional annotations to dashy helm chart for the Service. This will allow users to use a LoadBalancer service type and add annotations for [external-dns](https://github.com/kubernetes-sigs/external-dns) which will dynamically create DNS records in something like PiHole or CoreDNS for HomeLabbers.

**Describe Preferred Solution**

Be able to define something like this in the helm values
```
service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dashy.christianlowe.com
```

**Describe Alternatives**

Not sure of an alternative.

**Related Code**

See above

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes
- [ ] No
